name: snap
on:
  push:
    tags:
      - '*'
    branches:
      - humble
  pull_request:
    branches:
      - humble
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    strategy:
      matrix:
        platform:
        - amd64
        - arm64
    steps:
    - uses: actions/checkout@v3
      with:
        # full history for latest tag name
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v1
    - uses: snapcore/action-build@v1
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: build-snap
      with:
        snapcraft-args: '--enable-experimental-extensions'
        architecture: ${{ matrix.platform }}

    # Make sure the snap is installable
    - run: |
        sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}

    # @todo Do some testing with the snap
    - run: |
        micro-ros-agent udp4
    - uses: actions/upload-artifact@v3
      with:
        name: micro-ros-agent-snap
        path: ${{ steps.build-snap.outputs.snap }}

  publish:
    if: github.ref == 'refs/heads/foxy' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        architecture:
        - amd64
        - arm64
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: micro-ros-agent-snap
        path: .
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{needs.build.outputs.snap-file}}
        release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}